name: pt
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cudatoolkit
  - ffmpeg
  - freetype
  - giflib
  - gmp
  - gnutls
  - idna
  - intel-openmp
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libiconv
  - libidn2
  - libpng
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libwebp
  - libwebp-base
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - numpy
  - numpy-base
  - openh264
  - openssl
  - pillow
  - pip
  - pycparser
  - pyopenssl
  - pysocks
  - python
  - pytorch
  - pytorch-mutex
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - torchvision
  - typing_extensions
  - urllib3
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - absl-py
    - aiohttp
    - aiosignal
    - albumentations
    - argon2-cffi
    - argon2-cffi-bindings
    - arrow
    - async-timeout
    - asynctest
    - attrs
    - backcall
    - beautifulsoup4
    - binaryornot
    - bleach
    - cachetools
    - chardet
    - click
    - cookiecutter
    - cycler
    - debugpy
    - decorator
    - defusedxml
    - docker-pycreds
    - efficientnet-pytorch
    - entrypoints
    - evalutils
    - fastjsonschema
    - fonttools
    - frozenlist
    - fsspec
    - future
    - gitdb
    - gitpython
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - imageio
    - imgaug
    - importlib-metadata
    - importlib-resources
    - imutils
    - install
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - jinja2-time
    - joblib
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyterlab-pygments
    - jupyterlab-widgets
    - kiwisolver
    - markdown
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mediapipe
    - mistune
    - multidict
    - munch
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - notebook
    - oauthlib
    - opencv-contrib-python
    - opencv-python
    - opencv-python-headless
    - packaging
    - pandas
    - pandocfilters
    - parso
    - pathtools
    - pexpect
    - pickleshare
    - pretrainedmodels
    - prometheus-client
    - promise
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - pyasn1
    - pyasn1-modules
    - pydeprecate
    - pygments
    - pyparsing
    - pyrsistent
    - python-dateutil
    - python-slugify
    - pytorch-lightning
    - pytz
    - pywavelets
    - pyyaml
    - pyzmq
    - qudida
    - requests
    - requests-oauthlib
    - rsa
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - send2trash
    - sentry-sdk
    - setproctitle
    - shapely
    - shortuuid
    - simpleitk
    - smmap
    - soupsieve
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - terminado
    - text-unidecode
    - threadpoolctl
    - tifffile
    - timm
    - tinycss2
    - torchmetrics
    - tornado
    - tqdm
    - traitlets
    - wandb
    - wcwidth
    - webencodings
    - werkzeug
    - widgetsnbextension
    - yarl
    - zipp